PRODUCTS = [
    {"id": 1, "name": "Flover Bear", "emoji": "🌸", "category": "gifts", "price": 14000},
    {"id": 2, "name": "Omadli Bear", "emoji": "🍀", "category": "gifts", "price": 14000},
    {"id": 3, "name": "Rabbit Bear", "emoji": "🐰", "category": "gifts", "price": 14000},
    {"id": 4, "name": "Usta Bear", "emoji": "🔧", "category": "gifts", "price": 14000},
    {"id": 5, "name": "Yurakli Ayiq", "emoji": "💝", "category": "gifts", "price": 14000},
    {"id": 6, "name": "Clown Bear", "emoji": "🤡", "category": "gifts", "price": 14000},
    {"id": 7, "name": "Yangi Yil Bear", "emoji": "🎄", "category": "gifts", "price": 14000},
    {"id": 8, 'name': 'Yurak "LOVE"', "emoji": "❤️", "category": "gifts", "price": 14000},
    {"id": 9, "name": "Archa", "emoji": "🌲", "category": "gifts", "price": 14000},
    {"id": 10, "name": "3 Oylik Premium", "emoji": "⭐", "category": "premium", "price": 169000},
    {"id": 11, "name": "6 Oylik Premium", "emoji": "⭐", "category": "premium", "price": 225000},
    {"id": 12, "name": "12 Oylik Premium", "emoji": "⭐", "category": "premium", "price": 409000},
    {"id": 13, "name": "50 Stars", "emoji": "✨", "category": "stars", "price": 10750},
    {"id": 14, "name": "100 Stars", "emoji": "✨", "category": "stars", "price": 21500},
    {"id": 15, "name": "250 Stars", "emoji": "✨", "category": "stars", "price": 53750},
    {"id": 16, "name": "60 UC", "emoji": "🎮", "category": "pubg", "price": 11600},
    {"id": 17, "name": "120 UC", "emoji": "🎮", "category": "pubg", "price": 23200},
    {"id": 18, "name": "180 UC", "emoji": "🎮", "category": "pubg", "price": 34800},
    {"id": 19, "name": "325 UC", "emoji": "🎮", "category": "pubg", "price": 59000},
    {"id": 20, "name": "110 Diamonds", "emoji": "💎", "category": "freefire", "price": 10400},
    {"id": 21, "name": "572 Diamonds", "emoji": "💎", "category": "freefire", "price": 52700},
    {"id": 22, "name": "2398 Diamonds", "emoji": "💎", "category": "freefire", "price": 202000},
]
